config/routes.rb
Rails.application.routes.draw do
  devise_for :trainers
  resources :trainers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root "clients#index"
  #get "clients" => "clients#index"
  #get "clients/:id" => "clients#show", as: "client"
  #get "client/:id/edit" => "clients#edit", as: "edit_client"
  #get "client/new" => "clients#new", as: "new_client"
  get :search, controller: :search
	resources :clients do
		resources :assessments, only: [:index]
	end

	resources :assessments, only: [:new, :create, :show, :edit, :update, :destroy]
	
  get "assessments" => "clients#index"
end

app/models/assessment.rb
class Assessment < ApplicationRecord
  belongs_to :client, inverse_of: :assessments
  has_one :knee, inverse_of: :assessment, dependent: :destroy
  has_one :hip, inverse_of: :assessment, dependent: :destroy
  has_one :shoulder, inverse_of: :assessment, dependent: :destroy
  has_one :scapula, inverse_of: :assessment, dependent: :destroy
  has_one :elbow, inverse_of: :assessment, dependent: :destroy
  has_one :wrist, inverse_of: :assessment, dependent: :destroy
  has_one :ankle, inverse_of: :assessment, dependent: :destroy
  has_one :core, inverse_of: :assessment, dependent: :destroy

  accepts_nested_attributes_for :knee, :hip, :shoulder, :scapula, :elbow, :wrist, :ankle, :core

 	scope :client_assessments, -> (client){where(client_id: client).order('created_at desc')}
  scope :most_recent, -> (client){}
  #scope :most_recent, -> (client){select(client_id: client, created_at: client).order('created_at asc').group(:client_id, :created_at)}
  

end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
	before_action :authenticate_trainer!

	def index
		@client = Client.find(params[:client_id])
		@assessments = Assessment.client_assessments(@client)
	end

	def show
		@assessment = Assessment.find(params[:id])
	end

	def edit
		@assessment = Assessment.find(params[:id])
	end

	def new
		@assessment = Assessment.new
		@assessment.scapula = Scapula.new
		@assessment.shoulder = Shoulder.new
		@assessment.knee = Knee.new
		@assessment.hip = Hip.new
		@assessment.elbow = Elbow.new
		@assessment.wrist = Wrist.new
		@assessment.ankle = Ankle.new
		@assessment.core = Core.new
	end

	def create
		@assessment = Assessment.new(assessment_params)
		if @assessment.save
			redirect_to @assessment
		else
			render :new
		end
	end

	def update
		@assessment = Assessment.find(params[:id])
		if @assessment.update(assessment_params)
			redirect_to @assessment
		else
			render :edit
		end
	end

	def destroy
		@assessment = Assessment.find(params[:id])
		@assessment.destroy
		redirect_to clients_path
	end

private

	def assessment_params
		params.require(:assessment).
		permit(:client_id,
			knee_attributes: [:assessment_id, :knee_flexion_left, :knee_flexion_right, :knee_extension_left, :knee_extension_right], 
			hip_attributes: [:assessment_id, :hip_flexion_right, :hip_flexion_left, :hip_extension_left, :hip_extension_right, :hip_abduction_left, :hip_abduction_right, :hip_adduction_left, :hip_adduction_right, :hip_internal_rotation_90_left, :hip_internal_rotation_90_right, :hip_external_rotation_90_left, :hip_external_rotation_90_right],
			shoulder_attributes: [:assessment_id, :shoulder_flexion_left, :shoulder_flexion_right, :shoulder_extension_left, :shoulder_extension_right, :shoulder_abduction_left, :shoulder_abduction_right, :shoulder_adduction_left, :shoulder_adduction_right, :shoulder_internal_rotation_left, :shoulder_internal_rotation_right, :shoulder_external_rotation_left, :shoulder_external_rotation_right, :shoulder_horizontal_abduction_left, :shoulder_horizontal_abduction_right, :shoulder_horizontal_adduction_left, :shoulder_horizontal_adduction_right],
			scapula_attributes: [:assessment_id, :scapula_elevation_left, :scapula_elevation_right, :scapula_depression_left, :scapula_depression_right, :scapula_protraction_left, :scapula_protraction_right, :scapula_retraction_left, :scapula_retraction_right, :scapula_upward_rotation_left, :scapula_upward_rotation_right, :scapula_downward_rotation_left, :scapula_downward_rotation_right],
			elbow_attributes: [:assessment_id, :elbow_flexion_supination_left, :elbow_flexion_supination_right, :elbow_extension_supination_left, :elbow_extension_supination_right, :elbow_flexion_neutral_left, :elbow_flexion_neutral_right, :elbow_extension_neutral_left, :elbow_extension_neutral_right, :elbow_flexion_pronation_left, :elbow_flexion_pronation_right, :elbow_extension_pronation_left, :elbow_extension_pronation_right],
			wrist_attributes: [:assessment_id, :wrist_flexion_left, :wrist_flexion_right, :wrist_extension_left, :wrist_extension_right, :wrist_radial_deviation_left, :wrist_radial_deviation_right, :wrist_ulnar_deviation_left, :wrist_ulnar_deviation_right],
			ankle_attributes: [:assessment_id, :ankle_plantar_flexion_left, :ankle_plantar_flexion_right, :ankle_dorsiflexion_left, :ankle_dorsiflexion_right, :ankle_inversion_left, :ankle_inversion_right, :ankle_eversion_left, :ankle_eversion_right],
			core_attributes: [:assessment_id, :trunk_lateral_flexion_left, :trunk_lateral_flexion_right, :trunk_rotation_left, :trunk_rotation_right, :trunk_flexion, :trunk_extension]
			)
	end
end

app/helpers/assessments_helper.rb
module AssessmentsHelper
	
	def muscle_balance(category, percentage)
		case category

		when 'Good Balance'
			content_tag(:div, number_to_percentage(percentage), class: ["bg-success", "text-white"])
		when 'Level 1 Imbalance'
			content_tag(:div, number_to_percentage(percentage), class: ["bg-level-one-imbalance", "text-gray"])
		when 'Level 2 Imbalance'
			content_tag(:div, number_to_percentage(percentage), class: ["bg-level-two-imbalance", "text-black"])	
		when 'Level 3 Imbalance'
			content_tag(:div, number_to_percentage(percentage), class: ["bg-level-three-imbalance", "text-white"])
		else

		end
	end

	def joint_data
		[
			{name: "Core", data: @assessment.core.overall_average}
		]
	end
end

app/views/assessments/_form.html.erb
<%= form_for @assessment, html: { class: "needs-validation was-validated", novalidate: 'novalidate'} do |f| %>
  <% if @assessment.errors.any? %>
  <section id="errors">
    <div class="alert alert-danger" role="alert">
    <header>
      <h2>
        Oops! The <%= @assessment.class.name.titleize.downcase %> could not be saved. 
      </h2>
      <h3>
        Please correct the following <%= pluralize(@assessment.errors.count, "error") %>:
      </h3>
    </header>
    <ul>
      <% @assessment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  </section>
  <% end %>

  <div style="padding-bottom: 20px; text-align: center;" class="col-sm">
    <%= f.select :client_id, Client.all.collect { |c| [c.name, c.id]}, {prompt: "-Select A Client-"}, { required: true, class: "form-control"} %> 
  </div>
        <h4>Lying on Back</h4>

  <%= render 'assessments/partials/lying_on_back', f: f %>

        <h4>Lying On Stomach</h4>

	<%= render 'assessments/partials/lying_on_stomach', f: f %>
	
        <h4>Seated On Edge of Table</h4>
 
	<%= render 'assessments/partials/seated_on_edge_of_table', f: f %>
	
        <h4>Bench Next To Wall</h4>
 
	<%= render 'assessments/partials/bench_next_to_wall', f: f %>
	
        <h4>Use Incline Bench</h4>
 
	<%= render 'assessments/partials/use_incline_bench', f: f %>
	
        <h4>Lying On Bench</h4>
 
    <%= render 'assessments/partials/lying_on_bench', f: f %>
	
        <h4>Seated In Chair</h4>
 
	<%= render 'assessments/partials/seated_in_chair', f: f %>
	
        <h4>Lying On Floor</h4>
 
   <%= render 'assessments/partials/lying_on_floor', f: f %>
	
    <%= f.submit "Submit Assessment", class: "btn btn-primary btn-lg btn-block" %>

<% end %>

app/views/assessments/edit.html.erb
<h2 align="center">Edit Assessment</h2>

<%= render 'form' %>

app/views/assessments/index.html.erb
	<% @assessments.each do |assessment| %>
		<ul><%= link_to assessment.created_at.strftime("%D"), assessment_path(assessment) %></ul>
	<% end %>

app/views/assessments/new.html.erb
	<h2 align="center">Start A New Assessment</h2>
	<%= render 'form' %>

app/views/assessments/show.html.erb
<div class="center">
	<h2><center><%= @assessment.client.name %>'s Assessment on <%= @assessment.created_at.strftime('%D') %></center></h2>
	<hr>
	<p style="padding-top: 40px;">
		<%= render 'assessments/assessment_results/overview_results' %>
	</p>
	<p style="padding-top: 40px;">
		<%= render 'assessments/assessment_results/core_results' %>
	</p>
	<p style="padding-top: 40px;">
		<%= render 'assessments/assessment_results/hip_results' %>
	</p>
	<p style="padding-top: 40px;">
		<%= render 'assessments/assessment_results/knee_results' %>
	</p>
	<p style="padding-top: 40px;">
		<%= render 'assessments/assessment_results/ankle_results' %>
	</p>
	<p style="padding-top: 40px;">
		<%= render 'assessments/assessment_results/scapula_results' %>
	</p>
	<p style="padding-top: 40px;">
		<%= render 'assessments/assessment_results/shoulder_results' %>
	</p>
	<p style="padding-top: 40px;">
		<%= render 'assessments/assessment_results/elbow_results' %>
	</p>
	<p style="padding-top: 40px;">
		<%= render 'assessments/assessment_results/wrist_results' %>
	</p>
</div>	
<% content_for :side do %>
	<a class="nav-link"><%= link_to 'All Clients', clients_path  %></a>
	<a class="nav-link"><%= link_to "Client's Page", client_path(@assessment.client) %></a>
	<a class="nav-link"><%= link_to 'Edit Assessment', edit_assessment_path(@assessment) %></a>
	<a class="nav-link"><%= link_to 'Delete Assessment', assessment_path(@assessment), method: :delete, data: { confirm: 'Are you sure you would like to delete?'} %></a>
	<hr>
	<h6>PDF Preview</h6>
	<p>1)PC: "Ctrl+P" | Mac: "Cmd+P"</p>
	<p>2)Click "More Settings"</p>
	<p>3)Set "Scale" to "125"</p>
	<p>4)Options: Check box for "Background graphics"</p>
	<p>5) PDF Viewer<br>Click "Open PDF in Preview"</p>




<% end %>