config/routes.rb
Rails.application.routes.draw do
  devise_for :trainers
  resources :trainers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root "clients#index"
  #get "clients" => "clients#index"
  #get "clients/:id" => "clients#show", as: "client"
  #get "client/:id/edit" => "clients#edit", as: "edit_client"
  #get "client/new" => "clients#new", as: "new_client"
  get :search, controller: :search
	resources :clients do
		resources :assessments, only: [:index]
	end

	resources :assessments, only: [:new, :create, :show, :edit, :update, :destroy]
	
  get "assessments" => "clients#index"
end

app/views/shared/_errors.html.erb
<% if @assessment.errors.any? %>
  <section id="errors">
    <header>
      <h2>
        Oops! The <%= @assessment.class.name.titleize.downcase %> could not be saved. 
      </h2>
      <h3>
        Please correct the following <%= pluralize(@assessment.errors.count, "error") %>:
      </h3>
    </header>
    <ul>
      <% @assessment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/shared/_navbar.html.erb
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="<%= clients_url %>">TNT Health & Fitness</a>
      
      <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search" data-behavior="autocomplete">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
        	<% if trainer_signed_in? %>
	        	<%= link_to "Sign Out", destroy_trainer_session_path, method: :delete, class: "nav-link" %>
	        <% else %>
	        	<div class="row justify-content-end">
		        	<div class="col-sm-5"><%= link_to "Sign In", new_trainer_session_path, class: "nav-link" %></div>
		        	<div class="col-sm-6"><%= link_to "Sign Up", new_trainer_registration_path, class: "nav-link" %></div>
		        </div>
	        <% end -%>
        </li>
      </ul>
    </nav>


  

app/views/shared/_sidebar.html.erb
<div class="container_fluid">
  <div class="row">
  	<nav class="col-md-2 d-none d-md-block bg-light sidebar d-print-none">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
		  	  <%= content_for(:side) %>
		  </li>
		</ul>
	  </div>	
	</nav>
  </div>
</div>