config/routes.rb
Rails.application.routes.draw do
  devise_for :trainers
  resources :trainers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root "clients#index"
  #get "clients" => "clients#index"
  #get "clients/:id" => "clients#show", as: "client"
  #get "client/:id/edit" => "clients#edit", as: "edit_client"
  #get "client/new" => "clients#new", as: "new_client"
  get :search, controller: :search
	resources :clients do
		resources :assessments, only: [:index]
	end

	resources :assessments, only: [:new, :create, :show, :edit, :update, :destroy]
	
  get "assessments" => "clients#index"
end

app/models/client.rb
class Client < ApplicationRecord
	has_many :assessments, inverse_of: :client, dependent: :destroy
	accepts_nested_attributes_for :assessments

	validates :name, :email, :phone, :date_of_birth, :home_address, presence: true
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
	before_action :authenticate_trainer!

	include Upcoming

	def index
		@clients = Client.all
		@assess_status = upcoming_assessments(@clients)
		@up_to_date = @assess_status["Up to Date"]
		@upcoming = @assess_status["Upcoming"]
		@past_due = @assess_status["Past Due"]
	end

	def show
		@client = Client.find(params[:id])
	end

	def edit
		@client = Client.find(params[:id])
	end

	def new
		@client = Client.new
	end

	def create
		@client = Client.new(client_params)
		if @client.save
			redirect_to @client
		else
			render :new
		end
	end

	def update
		@client = Client.find(params[:id])
		if @client.update(client_params)
			redirect_to @client
		else
			render :edit
		end
	end

	def destroy
		@client = Client.find(params[:id])
		@client.destroy
		redirect_to clients_path
	end

private

	def client_params
		params.require(:client).
			permit(:name, :email, :phone, :date_of_birth, :home_address)
	end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for @client, html: { class: "needs-validation was-validated", novalidate: 'novalidate'} do |f| %>
	<% if @client.errors.any? %>
	  <section id="errors">
	  	<div class="alert alert-danger" role="alert">
	    <header>
	      <h2>
	        Oops! The <%= @client.class.name.titleize.downcase %> could not be saved. 
	      </h2>
	      <h3>
	        Please correct the following <%= pluralize(@client.errors.count, "error") %>:
	      </h3>
	    </header>
	    <ul>
	      <% @client.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	    </ul>
	  </div>
	  </section>
	<% end %>
	<p>
		<%= f.label :name %></br>
		<%= f.text_field :name, required: true, class: "form-control col-6" %>
	</p>
	<p>
		<%= f.label :email %></br>
		<%= f.text_field :email, required: true, class: "form-control col-6" %>
	</p>
	<p>
		<%= f.label :phone %></br>
		<%= f.text_field :phone, required: true, class: "form-control col-6" %>
	</p>
	<p>
		<%= f.label :date_of_birth %></br>
		<%= f.text_field :date_of_birth, required: true, class: "form-control col-6" %>
	</p>
	<p>
		<%= f.label :home_address %></br>
		<%= f.text_field :home_address, required: true, class: "form-control col-6" %>
	</p>			
	<p style="margin-top: 40px;">
		<%= f.submit "Create New Client", class: "btn btn-primary btn-lg" %>
	</p>
<% end %>

app/views/clients/edit.html.erb
<div class="container">
	<h1>Edit: <%= @client.name%></h1>

	<%= render 'form' %>
</div>

app/views/clients/index.html.erb
		
<div class="container">	
  <div class="row">
	<div class="col">
		<h4><center><%= pluralize(@up_to_date.length, 'Up-to-Date Assessment') %></center></h4>
		<h6><center><i>These Clients Are Up to Date</i></center></h6>
		
			<% @up_to_date.each do |assessment| %>
			<center><%= link_to "#{assessment.client.name} | #{assessment.created_at.strftime('%D')}", client_path(assessment.client) %></center>
			<% end %>
		
	</div>
	<div class="col">
		<h4><center><%= pluralize(@upcoming.length, 'Upcoming  Assessment') %></center></h4>
		<h6><center><i>3-4 Weeks Since Last Assessment</i></center></h6>

			<% @upcoming.each do |assessment| %>
			<center><%= link_to "#{assessment.client.name} | #{assessment.created_at.strftime('%D')}", client_path(assessment.client) %></center>
			<% end %>
	</div>
	<div class="col">
		<h4><center><%= pluralize(@past_due.length, 'Overdue Assessment') %></center></h4>
		<h6><center><i>Assesments Completed More Than 4 Weeks Ago</i></center></h6>
			<% @past_due.each do |assessment| %>
			<center><%= link_to "#{assessment.client.name} | #{assessment.created_at.strftime('%D')}", client_path(assessment.client) %></center>
			<% end %>
	</div>
  </div>
</div>
	<% content_for :side do %>
		<a class="nav-link "><%= link_to 'Create New Client >>', new_client_path %></a>
		<a class="nav-link"><%= link_to 'Start New Assessment >>', new_assessment_path %></a>

	<% end %>

app/views/clients/new.html.erb
<div class="container">
	<h2>Create New Client</h2>

	<%= render 'form' %>
</div>

app/views/clients/show.html.erb
		<h1><%= @client.name %></h1>

		<ul>
			<ul><strong>Email:</strong> <%= @client.email %></ul>
			<ul><strong>Phone:</strong> <%= @client.phone %></ul>
			<ul><strong>Date of Birth:</strong> <%= @client.date_of_birth %></ul>
			<ul><strong>Home Address:</strong> <%= @client.home_address %></ul>
		</ul>

	<% content_for :side do %>
			<a class="nav-link"><%= link_to 'Start New Assessment >>', new_assessment_path %></a>
		    <a class="nav-link"><%= link_to "All Clients", clients_path %></a>
		    <a class="nav-link"><%= link_to "Edit Client", edit_client_path(@client) %></a>
		    <a class="nav-link"><%= link_to "Past Assessments", client_assessments_path(@client, @assessment) %></a>
		    <a class="nav-link"><%= link_to "Delete Client", client_path(@client), method: :delete, data: { confirm: 'Are you sure you would like to delete?'} %></a>
	<% end %>